site_name: OSG Operations
site_url: https://osg-htc.org/operations/
repo_url: https://github.com/osg-htc/operations/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme: 
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'  

extra_css:
  - css/extra.css

nav:
- Home: 'index.md'
- Services:
  - Installing GlideinWMS Factory: 'services/install-gwms-factory.md'
  - Topology Service: 'services/topology.md'
  - Topology and Contacts Data: 'services/topology-contacts-data.md'
  - Finalize Cache Registration: 'services/finalize-cache-registration.md'
  - Sending Announcements: 'services/sending-announcements.md'
  - GRACC Corrections: 'services/gracc-corrections.md'
  - Hosted CE Definitions: 'services/hosted-ce-definitions.md'
  - CE Monitoring Dashboards: 'services/ce-monitoring-dashboards.md'
  - Yum Repository:
    - Troubleshooting Guide for Yum Repository Scripts: 'troubleshooting/repository-scripts.md'
- Service Level Agreements:
  - General: 'SLA/general.md'
  - Access Point: 'SLA/access-point.md'
  - CE Collector: 'SLA/collector.md'
  - GRACC: 'SLA/gracc.md'
  - GWMS Factory: 'SLA/gwms-factory.md'
  - GWMS Frontend: 'SLA/gwms-frontend.md'
  - HTCSS Central Manager: 'SLA/htcss-central-manager.md'
  - Hosted CE: 'SLA/hosted-ce.md'
  - Message Broker: 'SLA/message-broker.md'
  - OASIS: 'SLA/oasis.md'
  - OSDF Core: 'SLA/osdf-core.md'
  - OSDF Cache: 'SLA/osdf-cache.md'
  - OSDF Origin: 'SLA/osdf-origin.md'
  - PerfSonar: 'SLA/perfsonar.md'
  - Software Repository: 'SLA/software-repo.md'
  - Topology: 'SLA/topology.md'
  - Web Pages: 'SLA/web-pages.md'
  - XDLogin: 'SLA/xdlogin.md'
- External OASIS repositories: 'external-oasis-repos.md'

markdown_extensions:
  - admonition
  - codehilite
#  - toc(permalink=true)
  - toc
#  - osg_markdown.colors
  - pymdownx.details
